export const AUDIT_ENTITY_TYPE = Object.freeze({
  CLIENT: 'CLIENT',
  BIKE: 'BIKE',
  WORK_ORDER: 'WORK_ORDER',
  WORK_ORDER_ITEM: 'WORK_ORDER_ITEM',
  USER: 'USER',
});

export const AUDIT_ENTITY_TYPES = Object.freeze(
  Object.values(AUDIT_ENTITY_TYPE),
);

export const AUDIT_ACTION = Object.freeze({
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  SOFT_DELETED: 'SOFT_DELETED',
  RESTORED: 'RESTORED',
  OWNER_CHANGED: 'OWNER_CHANGED',
  ASSIGNED: 'ASSIGNED',
  REASSIGNED: 'REASSIGNED',
  UNASSIGNED: 'UNASSIGNED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  REOPENED: 'REOPENED',
  CANCELLED: 'CANCELLED',
  ITEM_ADDED: 'ITEM_ADDED',
  ITEM_DELETED: 'ITEM_DELETED',
  ROLE_CHANGED: 'ROLE_CHANGED',
  ACTIVATED: 'ACTIVATED',
  DEACTIVATED: 'DEACTIVATED',
});

export const AUDIT_ACTIONS = Object.freeze(Object.values(AUDIT_ACTION));

export const AUDIT_TRANSITION_KIND = Object.freeze({
  FORWARD: 'FORWARD',
  REGRESSION: 'REGRESSION',
});
